FROM mhart/alpine-node:6.9
MAINTAINER Holi0317 "holliswuhollis@gmail.com"

# Copy necessary files
COPY . /srv/

# Build it
WORKDIR /srv/
RUN apk --update add --no-cache python make g++ \
  && npm install \
  && npm install --only=dev

ENTRYPOINT ["node_modules/.bin/gulp", "serve"]