language: node_js
node_js:
  - "stable"
  - "4.2"
cache:
  directories:
    - node_modules
before_script:
  - npm install -g gulp
  - cp config.template.js config.js
script: node_modules/mocha/bin/_mocha
