version: '2'
services:
  backend:
    build:
      context: ./
      dockerfile: dockerfiles/backend-dev
    image: holi0317/sms-library-helper-backend:dev
    mem_limit: 512m
    memswap_limit: 1g
    container_name: slh-backend-dev
    networks:
     - develop
    volumes:
      - ./config.yaml:/etc/slh-config.yaml
      - ./slh.sqlite:/data/db.sqlite
      - ./src/:srv/src/
      - ./custom-typings/:srv/custom-typings/
      - ./tasks/:srv/tasks/
      - ./test/:srv/test/

  frontend:
    build:
      context: ./
      dockerfile: dockerfiles/frontend-dev
    image: holi0317/sms-library-helper-frontend:dev
    mem_limit: 512m
    memswap_limit: 1g
    container_name: slh-frontend-dev
    networks:
     - develop
    volumes:
     - ./frontend/app/:/srv/app/
    links:
     - backend
    ports:
     - "3000:3000"
     - "3001:3001"

  timer:
    build:
      context: ./
      dockerfile: dockerfiles/timer-dev
    image: holi0317/sms-library-helper-timer:dev
    mem_limit: 512m
    memswap_limit: 1g
    container_name: slh-timer-dev
    networks:
     - develop
    volumes:
      - ./config.yaml:/etc/slh-config.yaml
      - ./slh.sqlite:/data/db.sqlite
      - ./src/:srv/src/
      - ./custom-typings/:srv/custom-typings/
      - ./tasks/:srv/tasks/
      - ./test/:srv/test/

networks:
  develop:
    driver: bridge