version: '2'
services:
  mongo:
    image: mongo:3.2
    mem_limit: 512m
    memswap_limit: 1g
    networks:
     - production
    volumes:
     - /srv/slh/mongodb:/data/db

  backend:
    build:
      context: ./backend
    image: sms-library-helper-backend:v0.0.1
    mem_limit: 512m
    memswap_limit: 1g
    networks:
     - production
    volumes:
      - /srv/slh/config.yaml:/etc/slh-config.yaml
    links:
     - mongo

  frontend:
    build:
      context: ./frontend
    image: sms-library-helper-frontend:v0.0.1
    mem_limit: 512m
    memswap_limit: 1g
    networks:
     - production
    volumes:
     - /srv/slh/certs/:/etc/nginx/certs
    links:
     - backend
    ports:
     - "80:80"
     - "443:443"

  timer:
    build:
      context: ./timer
    image: sms-library-helper-timer:v0.0.1
    mem_limit: 512m
    memswap_limit: 1g
    networks:
     - production
    volumes:
     - /srv/slh/config.yaml:/etc/slh-config.yaml
    links:
     - mongo

networks:
  production:
    driver: bridge