version: '2'
services:
  backend:
    build:
      context: ./
      dockerfile: dockerfiles/backend-dev
    image: holi0317/sms-library-helper-backend:dev
    mem_limit: 512m
    memswap_limit: 1g
    networks:
     - develop
    volumes:
      - ./config.yaml:/etc/slh-config.yaml
      - ./:srv/
      - ./slh.sqlite:/data/db.sqlite

  frontend:
    build:
      context: ./
      dockerfile: dockerfiles/frontend-dev
    image: holi0317/sms-library-helper-frontend:dev
    mem_limit: 512m
    memswap_limit: 1g
    networks:
     - develop
    volumes:
     - ./frontend/app/:/srv/app/
    links:
     - backend
    ports:
     - "3000:3000"
     - "3001:3001"

  timer:
    build:
      context: ./
      dockerfile: dockerfiles/timer-dev
    image: holi0317/sms-library-helper-timer:dev
    mem_limit: 512m
    memswap_limit: 1g
    networks:
     - develop
    volumes:
     - ./config.yaml:/etc/slh-config.yaml
     - ./:srv/
     - ./slh.sqlite:/data/db.sqlite

networks:
  develop:
    driver: bridge